#!/usr/bin/env bash

token_="372561263:AAEvPVDnGkfV3D7TGm0xVwY3dtJc5v3_Drc"

function print_logo() {

 echo -e "\e[38;5;77m" 

echo -e "يـعـ๋͜مل الـبوت ع مـجموعـات  30k🌝💋
مـ๋͜ن تـطـ๋͜وير 🌝👇
<@TEAM_ALANBR> 
تـابـ๋͜عـنـ๋͜ا 😸❤️
<@TEAM_ALANBR>"

echo -e "  "

echo -e "  "

echo -e "  __ CH : @TEAM_ALANBR  "

echo -e "  \e[38;5;88m"

echo -e ""

echo -e ""

echo -e ""

echo -e "\e[33m  __ CH : @TEAM_ALANBR    
\e[0m"

echo -e "\e[33m |\e[0m"

echo -e "\e[33m |\e[0m"

echo -e "\e[33m |\e[0m"

echo -e "\e[33m |\e[0m"

echo -e "\e[33m \e[0m"

}


if [ ! -f ./libs/tgcli ]; then

echo -e ""

echo -e "\e[33m  __ CH : @TEAM_ALANBR
"

echo -e "\e[33m |"

echo -e "\e[33m |"

echo -e "\e[33m |"

echo -e "\e[33m |"

echo -e "\e[33m "

    echo "\e[31;1mtg not found"

    echo "Run $0 install"

    exit 1

 fi

if [ ! $token_ ]; then

echo -e ""

echo -e "\e[33m  __ CH : @TEAM_ALANBR
"

echo -e "\e[33m |"

echo -e "\e[33m |"

echo -e "\e[33m |"

echo -e "\e[33m |"

echo -e "\e[33m \e[0m"

  echo -e "\e[31;1mToken Not found\e"

 exit 1

 fi



  print_logo

   echo -e ""

echo -e ""

echo -e " \e[38;5;300mOperation |  جاري تشغيل البوت ☑️📌¦"

echo -e " Source | TEAM_ALANBR 2018"

echo -e " "

echo -e " "

echo -e " "

echo -e " "

echo -e " "

echo -e " "

echo -e " "

echo -e " \e[38;5;40m"


curl "https://api.telegram.org/bot"$token_"/sendmessage" -F

./libs/tgcli -s ./bot/bot.lua $@ --bot=$token_
